version: "3"

services:
  web:
    image: weather:latest
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./db.sqlite3:/code/db.sqlite3
